target: all

all:
	 g++ -std=c++11 code/Pong.cpp code/Starship.cpp code/ECE_Centipede.cpp code/ECE_LaserBlast.cpp code/Mushroom.cpp -o Pong -Icode/ -I/opt/SFML/include -L/opt/SFML/lib -lsfml-graphics -lsfml-system -lsfml-window
